### ISSUE TITLE
Failed to execute generate command

### ISSUE THREAD

**Issue by DonnC** [RyanDsilva/feature_folder_cli#1]
Hello, was going through your article and tried the cli
how ever im getting this issue

```bash
Can't load Kernel binary: Invalid SDK hash.                                                                             
feature_folder_cli 0.0.4 requires the Flutter SDK, which is unsupported for global executables.
```

**Comment by smartdev123** [comment]
> Hello, was going through your article and tried the cli how ever im getting this issue
> 
> ```shell
> Can't load Kernel binary: Invalid SDK hash.                                                                             
> feature_folder_cli 0.0.4 requires the Flutter SDK, which is unsupported for global executables.
> ```

how have you installed the package ? By using it as a library i think! If you want to generate a folder_by_feature project try using this package as an executable by using the `dart pub global activate feature_folder_cli` . Follow the official documentation on https://pub.dev/packages/feature_folder_cli/install
