### ISSUE TITLE
Mason Cache File Deletion Failure During Generation

### ISSUE THREAD

**Issue by jlambright** [RyanDsilva/feature_folder_cli#3]
` FileSystemException: Deletion failed, path = 'C:\Users\jlambright\AppData\Local\Mason\Cache\git\feature_folder_cli_aHR0cHM6Ly9naXRodWIuY29tL1J5YW5Ec2lsdmEvZmVhdHVyZV9mb2xkZXJfY2xp_efb98f7bcbaaa7b1aded22abcf8654c33ec6456f' (OS Error: The system cannot find the path specified.
, errno = 3)`

Has this been seen? Happens after reactivating the package as well.

**Comment by jlambright** [comment]
Somehow the ..\Mason folder was set to read-only by the OS. Perhaps a folder permissions check would catch this?

**Comment by jlambright** [comment]
Spoke too soon. After one successful generation, the ..\Mason folder becomes read-only again.

**Comment by RyanDsilva** [comment]
Hi @jlambright, could you specify the steps to replicate this? Works fine for me throughout multiple generations across projects. I am on macOS though.

**Comment by jlambright** [comment]
Sorry for the late reply. Here is currently what happens.

```
ff generate -n dispatch -t getx

Time Taken: 21 milliseconds

✓ Feature dispatch created successfully
✖ FileSystemException: Deletion failed, path = 'C:\Users\jlambright\AppData\Local\Mason\Cache\git\feature_folder_cli_aHR0cHM6Ly9naXRodWIuY29tL1J5YW5Ec2lsdmEvZmVhdHVyZV9mb2xkZXJfY2xp_efb98f7bcbaaa7b1aded22abcf8654c33ec6456f' (OS Error: The system cannot find the path specified.
, errno = 3)
```

**Comment by s-mikita** [comment]
Issue can be replicated on Win10 machine.
Only happens when using `-t getx` to generate getx brick template. Seems like somehere in the brick is an error or mason need's a bump in version.

**Comment by RyanDsilva** [comment]
@jlambright @nikitka5702 I have bumped up the versions and tested. Could you try again?
