### ISSUE TITLE
Need more details to use this plugins and update

### ISSUE THREAD

**Issue by parmeetmaster** [RyanDsilva/feature_folder_cli#4]
Hello Sir,

Can you add some more details about this plugin like installation instructions and activation?
Also, we are not able to understand why features and types are there. Like What kind of type is supported.
I hope you will update the documentation of this plugin so more users can understand how to make a hierarchy with this.

Also this plugin is outdated since 9 months ago kindly update this plugin with a new flutter sdk environment.

![image](https://user-images.githubusercontent.com/42370506/234167521-8e87d30b-235e-4732-b9bf-1ba965546cec.png)

**Comment by RyanDsilva** [comment]
@parmeetmaster thanks for the interest, I have taken this up and would be working on this over the weekend.

**Comment by RyanDsilva** [comment]
@parmeetmaster I have bumped up mason version and it should be very easy to use, you can just generate a dummy structure and inspect the generated files. That would be the best way to evaluate this.

**Comment by parmeetmaster** [comment]
Kindly add more instructions in readme.md.Or add an youtube link so i can do this.
