### ISSUE TITLE
✖ Instance of 'BrickIncompatibleMasonVersion'

### ISSUE THREAD

**Issue by Uvais-Iocod** [RyanDsilva/feature_folder_cli#5]
While i tried to build a feature, i'm getting following error

`✖ Instance of 'BrickIncompatibleMasonVersion'`
![Screenshot 2023-05-16 at 5 00 43 PM](https://github.com/RyanDsilva/feature_folder_cli/assets/122770630/61759635-5be4-4ffd-be44-ca15e14953f9)

What should i do? Thanks in advance

**Comment by RyanDsilva** [comment]
@Uvais-Iocod I have bumped mason versions and tested this. Should be good to go now. You would need to update the version to `0.3.0`

**Comment by Uvais-Iocod** [comment]
Its working fine after updated version to  `0.3.0`. Thanks @RyanDsilva for your valuable support.
